### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [infodox/python-pty-shells#2]
I am  a developer for the ArchAssault project and we would like to add this repo to our distribution list. Can you add a license file to the repo please?

**Comment by infodox** [comment]
Licence is WTFPL as per README.md file. 

Added it as LICENCE.md :)

Will be updating some of the code soon also, there was a commit fuckup where I committed a buggy bit of code somewhere and cannot remember which bit it was!

**Comment by archey** [comment]
Thanks I will  get the pkgbuild built and over to our repo, I noticed this because we are building tools from @Chokepoint's repo and he mentioned this one.
